DROP TABLE IF EXISTS WEATHER_INFO;
 
CREATE TABLE WEATHER_INFO (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  api_url VARCHAR(250) NOT NULL,
  api_key VARCHAR(250) NOT NULL,
  request VARCHAR(250) NOT NULL,
  response VARCHAR(20000) DEFAULT NULL
);